name: Python CI Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code to check
        uses: actions/checkout@v1
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install all necessary packages, including dev dependencies.
          pip install -e ."[dev]"
      - name: Check format with black
        run: |
          # Check all python files to see if black would format them.
          # If black would format them, then the check fails.
          black --check **/*.py
      - name: Lint with flake8
        run: |
          # exit-zero treats all errors as warnings.
          flake8 .
      - name: Test with unittest
        run: |
          python -m unittest discover -s tests/
